# Generated by Django 2.0.4 on 2018-04-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompeteInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instr', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='compete_instr',
            field=models.ManyToManyField(to='apps.CompeteInstruction'),
        ),
    ]
