# Generated by Django 2.0.4 on 2018-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20180414_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='compete_time',
            field=models.IntegerField(default=20),
        ),
    ]
